// This file is auto-generated by @hey-api/openapi-ts

export const BearerResponseSchema = {
  properties: {
    access_token: {
      type: 'string',
      title: 'Access Token',
    },
    token_type: {
      type: 'string',
      title: 'Token Type',
    },
  },
  type: 'object',
  required: ['access_token', 'token_type'],
  title: 'BearerResponse',
} as const;

export const Body_auth_jwt_login_auth_jwt_login_postSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: 'string',
          pattern: '^password$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Grant Type',
    },
    username: {
      type: 'string',
      title: 'Username',
    },
    password: {
      type: 'string',
      format: 'password',
      title: 'Password',
    },
    scope: {
      type: 'string',
      title: 'Scope',
      default: '',
    },
    client_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Client Id',
    },
    client_secret: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      format: 'password',
      title: 'Client Secret',
    },
  },
  type: 'object',
  required: ['username', 'password'],
  title: 'Body_auth_jwt_login_auth_jwt_login_post',
} as const;

export const Body_reset_forgot_password_auth_forgot_password_postSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
  },
  type: 'object',
  required: ['email'],
  title: 'Body_reset_forgot_password_auth_forgot_password_post',
} as const;

export const Body_reset_reset_password_auth_reset_password_postSchema = {
  properties: {
    token: {
      type: 'string',
      title: 'Token',
    },
    password: {
      type: 'string',
      title: 'Password',
    },
  },
  type: 'object',
  required: ['token', 'password'],
  title: 'Body_reset_reset_password_auth_reset_password_post',
} as const;

export const Body_verify_request_token_auth_request_verify_token_postSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
  },
  type: 'object',
  required: ['email'],
  title: 'Body_verify_request_token_auth_request_verify_token_post',
} as const;

export const Body_verify_verify_auth_verify_postSchema = {
  properties: {
    token: {
      type: 'string',
      title: 'Token',
    },
  },
  type: 'object',
  required: ['token'],
  title: 'Body_verify_verify_auth_verify_post',
} as const;

export const ErrorModelSchema = {
  properties: {
    detail: {
      anyOf: [
        {
          type: 'string',
        },
        {
          additionalProperties: {
            type: 'string',
          },
          type: 'object',
        },
      ],
      title: 'Detail',
    },
  },
  type: 'object',
  required: ['detail'],
  title: 'ErrorModel',
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const TaskSchema = {
  properties: {
    title: {
      type: 'string',
      maxLength: 200,
      minLength: 1,
      title: 'Title',
      description: '任务标题',
    },
    description: {
      anyOf: [
        {
          type: 'string',
          maxLength: 2000,
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
      description: '任务描述',
    },
    is_completed: {
      type: 'boolean',
      title: 'Is Completed',
      description: '是否完成',
      default: false,
    },
    priority: {
      type: 'integer',
      maximum: 3,
      minimum: 1,
      title: 'Priority',
      description: '优先级(1-低, 2-中, 3-高)',
      default: 1,
    },
    category: {
      type: 'string',
      maxLength: 100,
      title: 'Category',
      description: '任务分类',
      default: '未分类',
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: ['title', 'id', 'created_at', 'updated_at'],
  title: 'Task',
} as const;

export const TaskCreateSchema = {
  properties: {
    title: {
      type: 'string',
      maxLength: 200,
      minLength: 1,
      title: 'Title',
      description: '任务标题',
    },
    description: {
      anyOf: [
        {
          type: 'string',
          maxLength: 2000,
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
      description: '任务描述',
    },
    is_completed: {
      type: 'boolean',
      title: 'Is Completed',
      description: '是否完成',
      default: false,
    },
    priority: {
      type: 'integer',
      maximum: 3,
      minimum: 1,
      title: 'Priority',
      description: '优先级(1-低, 2-中, 3-高)',
      default: 1,
    },
    category: {
      type: 'string',
      maxLength: 100,
      title: 'Category',
      description: '任务分类',
      default: '未分类',
    },
  },
  type: 'object',
  required: ['title'],
  title: 'TaskCreate',
} as const;

export const TaskSummarySchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    is_completed: {
      type: 'boolean',
      title: 'Is Completed',
    },
    priority: {
      type: 'integer',
      title: 'Priority',
    },
    category: {
      type: 'string',
      title: 'Category',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
  },
  type: 'object',
  required: [
    'id',
    'title',
    'is_completed',
    'priority',
    'category',
    'created_at',
  ],
  title: 'TaskSummary',
} as const;

export const TaskUpdateSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: 'string',
          maxLength: 200,
          minLength: 1,
        },
        {
          type: 'null',
        },
      ],
      title: 'Title',
    },
    description: {
      anyOf: [
        {
          type: 'string',
          maxLength: 2000,
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    is_completed: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Completed',
    },
    priority: {
      anyOf: [
        {
          type: 'integer',
          maximum: 3,
          minimum: 1,
        },
        {
          type: 'null',
        },
      ],
      title: 'Priority',
    },
    category: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Category',
    },
  },
  type: 'object',
  title: 'TaskUpdate',
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      title: 'Password',
    },
    is_active: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Active',
      default: true,
    },
    is_superuser: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Superuser',
      default: false,
    },
    is_verified: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Verified',
      default: false,
    },
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserCreate',
  description: 'Schema for creating a new user.',
} as const;

export const UserReadSchema = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true,
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false,
    },
    is_verified: {
      type: 'boolean',
      title: 'Is Verified',
      default: false,
    },
  },
  type: 'object',
  required: ['id', 'email'],
  title: 'UserRead',
  description: 'Schema for returning user info.',
} as const;

export const UserUpdateSchema = {
  properties: {
    password: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Password',
    },
    email: {
      anyOf: [
        {
          type: 'string',
          format: 'email',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    is_active: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Active',
    },
    is_superuser: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Superuser',
    },
    is_verified: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Verified',
    },
  },
  type: 'object',
  title: 'UserUpdate',
  description: 'Schema for updating an existing user.',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
    input: {
      title: 'Input',
    },
    ctx: {
      type: 'object',
      title: 'Context',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
