// This file is auto-generated by @hey-api/openapi-ts
import { urlSearchParamsBodySerializer, } from './client';
import { client } from './client.gen';
import { completeTaskDeeptodosCompleteTaskTaskIdPostResponseTransformer, createTaskDeeptodosCreateTaskPostResponseTransformer, readTaskDeeptodosReadTaskTaskIdGetResponseTransformer, readTasksDeeptodosReadTasksGetResponseTransformer, readTasksSummaryDeeptodosReadTasksSummaryGetResponseTransformer, updateTaskDeeptodosUpdateTaskTaskIdPatchResponseTransformer, } from './transformers.gen';
/**
 * Auth:Jwt.Login
 */
export const authJwtLoginAuthJwtLoginPost = (options) => (options.client ?? client).post({
    ...urlSearchParamsBodySerializer,
    url: '/auth/jwt/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers,
    },
});
/**
 * Auth:Jwt.Logout
 */
export const authJwtLogoutAuthJwtLogoutPost = (options) => (options?.client ?? client).post({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/jwt/logout',
    ...options,
});
/**
 * Register:Register
 */
export const registerRegisterAuthRegisterPost = (options) => (options.client ?? client).post({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Reset:Forgot Password
 */
export const resetForgotPasswordAuthForgotPasswordPost = (options) => (options.client ?? client).post({
    url: '/auth/forgot-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Reset:Reset Password
 */
export const resetResetPasswordAuthResetPasswordPost = (options) => (options.client ?? client).post({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Verify:Request-Token
 */
export const verifyRequestTokenAuthRequestVerifyTokenPost = (options) => (options.client ?? client).post({
    url: '/auth/request-verify-token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Verify:Verify
 */
export const verifyVerifyAuthVerifyPost = (options) => (options.client ?? client).post({
    url: '/auth/verify',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Users:Current User
 */
export const usersCurrentUserUsersMeGet = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
});
/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUserUsersMePatch = (options) => (options.client ?? client).patch({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Users:Delete User
 */
export const usersDeleteUserUsersIdDelete = (options) => (options.client ?? client).delete({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options,
});
/**
 * Users:User
 */
export const usersUserUsersIdGet = (options) => (options.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options,
});
/**
 * Users:Patch User
 */
export const usersPatchUserUsersIdPatch = (options) => (options.client ?? client).patch({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Authenticated Route
 */
export const authenticatedRouteAuthenticatedRouteGet = (options) => (options?.client ?? client).get({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/authenticated-route',
    ...options,
});
/**
 * Create Task
 *
 * 创建新任务
 */
export const createTaskDeeptodosCreateTaskPost = (options) => (options.client ?? client).post({
    responseTransformer: createTaskDeeptodosCreateTaskPostResponseTransformer,
    url: '/deeptodos/create-task',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Read Tasks
 *
 * 获取任务列表（支持过滤和搜索）
 */
export const readTasksDeeptodosReadTasksGet = (options) => (options?.client ?? client).get({
    responseTransformer: readTasksDeeptodosReadTasksGetResponseTransformer,
    url: '/deeptodos/read-tasks',
    ...options,
});
/**
 * Read Tasks Summary
 *
 * 获取简要任务列表
 */
export const readTasksSummaryDeeptodosReadTasksSummaryGet = (options) => (options?.client ?? client).get({
    responseTransformer: readTasksSummaryDeeptodosReadTasksSummaryGetResponseTransformer,
    url: '/deeptodos/read-tasks-summary',
    ...options,
});
/**
 * Read Categories
 *
 * 获取所有分类
 */
export const readCategoriesDeeptodosReadCategoriesGet = (options) => (options?.client ?? client).get({ url: '/deeptodos/read-categories', ...options });
/**
 * Read Task
 *
 * 根据ID获取任务
 */
export const readTaskDeeptodosReadTaskTaskIdGet = (options) => (options.client ?? client).get({
    responseTransformer: readTaskDeeptodosReadTaskTaskIdGetResponseTransformer,
    url: '/deeptodos/read-task/{task_id}',
    ...options,
});
/**
 * Update Task
 *
 * 更新任务
 */
export const updateTaskDeeptodosUpdateTaskTaskIdPatch = (options) => (options.client ?? client).patch({
    responseTransformer: updateTaskDeeptodosUpdateTaskTaskIdPatchResponseTransformer,
    url: '/deeptodos/update-task/{task_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers,
    },
});
/**
 * Delete Task
 *
 * 删除任务
 */
export const deleteTaskDeeptodosDeleteTaskTaskIdDelete = (options) => (options.client ?? client).delete({ url: '/deeptodos/delete-task/{task_id}', ...options });
/**
 * Complete Task
 *
 * 标记任务为完成
 */
export const completeTaskDeeptodosCompleteTaskTaskIdPost = (options) => (options.client ?? client).post({
    responseTransformer: completeTaskDeeptodosCompleteTaskTaskIdPostResponseTransformer,
    url: '/deeptodos/complete-task/{task_id}',
    ...options,
});
