// This file is auto-generated by @hey-api/openapi-ts

import type {
  CompleteTaskDeeptodosCompleteTaskTaskIdPostResponse,
  CreateTaskDeeptodosCreateTaskPostResponse,
  ReadTaskDeeptodosReadTaskTaskIdGetResponse,
  ReadTasksDeeptodosReadTasksGetResponse,
  ReadTasksSummaryDeeptodosReadTasksSummaryGetResponse,
  UpdateTaskDeeptodosUpdateTaskTaskIdPatchResponse,
} from './types.gen';

const taskSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const createTaskDeeptodosCreateTaskPostResponseTransformer = async (
  data: any
): Promise<CreateTaskDeeptodosCreateTaskPostResponse> => {
  data = taskSchemaResponseTransformer(data);
  return data;
};

export const readTasksDeeptodosReadTasksGetResponseTransformer = async (
  data: any
): Promise<ReadTasksDeeptodosReadTasksGetResponse> => {
  data = data.map((item: any) => taskSchemaResponseTransformer(item));
  return data;
};

const taskSummarySchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const readTasksSummaryDeeptodosReadTasksSummaryGetResponseTransformer =
  async (
    data: any
  ): Promise<ReadTasksSummaryDeeptodosReadTasksSummaryGetResponse> => {
    data = data.map((item: any) => taskSummarySchemaResponseTransformer(item));
    return data;
  };

export const readTaskDeeptodosReadTaskTaskIdGetResponseTransformer = async (
  data: any
): Promise<ReadTaskDeeptodosReadTaskTaskIdGetResponse> => {
  data = taskSchemaResponseTransformer(data);
  return data;
};

export const updateTaskDeeptodosUpdateTaskTaskIdPatchResponseTransformer =
  async (
    data: any
  ): Promise<UpdateTaskDeeptodosUpdateTaskTaskIdPatchResponse> => {
    data = taskSchemaResponseTransformer(data);
    return data;
  };

export const completeTaskDeeptodosCompleteTaskTaskIdPostResponseTransformer =
  async (
    data: any
  ): Promise<CompleteTaskDeeptodosCompleteTaskTaskIdPostResponse> => {
    data = taskSchemaResponseTransformer(data);
    return data;
  };
