// This file is auto-generated by @hey-api/openapi-ts
const taskSchemaResponseTransformer = (data) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};
export const createTaskDeeptodosCreateTaskPostResponseTransformer = async (data) => {
    data = taskSchemaResponseTransformer(data);
    return data;
};
export const readTasksDeeptodosReadTasksGetResponseTransformer = async (data) => {
    data = data.map((item) => taskSchemaResponseTransformer(item));
    return data;
};
const taskSummarySchemaResponseTransformer = (data) => {
    data.created_at = new Date(data.created_at);
    return data;
};
export const readTasksSummaryDeeptodosReadTasksSummaryGetResponseTransformer = async (data) => {
    data = data.map((item) => taskSummarySchemaResponseTransformer(item));
    return data;
};
export const readTaskDeeptodosReadTaskTaskIdGetResponseTransformer = async (data) => {
    data = taskSchemaResponseTransformer(data);
    return data;
};
export const updateTaskDeeptodosUpdateTaskTaskIdPatchResponseTransformer = async (data) => {
    data = taskSchemaResponseTransformer(data);
    return data;
};
export const completeTaskDeeptodosCompleteTaskTaskIdPostResponseTransformer = async (data) => {
    data = taskSchemaResponseTransformer(data);
    return data;
};
