// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth_jwt_login_auth_jwt_login_post
 */
export type BodyAuthJwtLoginAuthJwtLoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * Body_reset_forgot_password_auth_forgot_password_post
 */
export type BodyResetForgotPasswordAuthForgotPasswordPost = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_reset_reset_password_auth_reset_password_post
 */
export type BodyResetResetPasswordAuthResetPasswordPost = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_verify_request_token_auth_request_verify_token_post
 */
export type BodyVerifyRequestTokenAuthRequestVerifyTokenPost = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_verify_verify_auth_verify_post
 */
export type BodyVerifyVerifyAuthVerifyPost = {
  /**
   * Token
   */
  token: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Task
 */
export type Task = {
  /**
   * Title
   *
   * 任务标题
   */
  title: string;
  /**
   * Description
   *
   * 任务描述
   */
  description?: string | null;
  /**
   * Is Completed
   *
   * 是否完成
   */
  is_completed?: boolean;
  /**
   * Priority
   *
   * 优先级(1-低, 2-中, 3-高)
   */
  priority?: number;
  /**
   * Category
   *
   * 任务分类
   */
  category?: string;
  /**
   * Id
   */
  id: string;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
  /**
   * Title
   *
   * 任务标题
   */
  title: string;
  /**
   * Description
   *
   * 任务描述
   */
  description?: string | null;
  /**
   * Is Completed
   *
   * 是否完成
   */
  is_completed?: boolean;
  /**
   * Priority
   *
   * 优先级(1-低, 2-中, 3-高)
   */
  priority?: number;
  /**
   * Category
   *
   * 任务分类
   */
  category?: string;
};

/**
 * TaskSummary
 */
export type TaskSummary = {
  /**
   * Id
   */
  id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Is Completed
   */
  is_completed: boolean;
  /**
   * Priority
   */
  priority: number;
  /**
   * Category
   */
  category: string;
  /**
   * Created At
   */
  created_at: Date;
};

/**
 * TaskUpdate
 */
export type TaskUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Is Completed
   */
  is_completed?: boolean | null;
  /**
   * Priority
   */
  priority?: number | null;
  /**
   * Category
   */
  category?: string | null;
};

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * UserRead
 *
 * Schema for returning user info.
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
};

/**
 * UserUpdate
 *
 * Schema for updating an existing user.
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type AuthJwtLoginAuthJwtLoginPostData = {
  body: BodyAuthJwtLoginAuthJwtLoginPost;
  path?: never;
  query?: never;
  url: '/auth/jwt/login';
};

export type AuthJwtLoginAuthJwtLoginPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginAuthJwtLoginPostError =
  AuthJwtLoginAuthJwtLoginPostErrors[keyof AuthJwtLoginAuthJwtLoginPostErrors];

export type AuthJwtLoginAuthJwtLoginPostResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginAuthJwtLoginPostResponse =
  AuthJwtLoginAuthJwtLoginPostResponses[keyof AuthJwtLoginAuthJwtLoginPostResponses];

export type AuthJwtLogoutAuthJwtLogoutPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/jwt/logout';
};

export type AuthJwtLogoutAuthJwtLogoutPostErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutAuthJwtLogoutPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterAuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type RegisterRegisterAuthRegisterPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterAuthRegisterPostError =
  RegisterRegisterAuthRegisterPostErrors[keyof RegisterRegisterAuthRegisterPostErrors];

export type RegisterRegisterAuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterAuthRegisterPostResponse =
  RegisterRegisterAuthRegisterPostResponses[keyof RegisterRegisterAuthRegisterPostResponses];

export type ResetForgotPasswordAuthForgotPasswordPostData = {
  body: BodyResetForgotPasswordAuthForgotPasswordPost;
  path?: never;
  query?: never;
  url: '/auth/forgot-password';
};

export type ResetForgotPasswordAuthForgotPasswordPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordAuthForgotPasswordPostError =
  ResetForgotPasswordAuthForgotPasswordPostErrors[keyof ResetForgotPasswordAuthForgotPasswordPostErrors];

export type ResetForgotPasswordAuthForgotPasswordPostResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordAuthResetPasswordPostData = {
  body: BodyResetResetPasswordAuthResetPasswordPost;
  path?: never;
  query?: never;
  url: '/auth/reset-password';
};

export type ResetResetPasswordAuthResetPasswordPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordAuthResetPasswordPostError =
  ResetResetPasswordAuthResetPasswordPostErrors[keyof ResetResetPasswordAuthResetPasswordPostErrors];

export type ResetResetPasswordAuthResetPasswordPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostData = {
  body: BodyVerifyRequestTokenAuthRequestVerifyTokenPost;
  path?: never;
  query?: never;
  url: '/auth/request-verify-token';
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostError =
  VerifyRequestTokenAuthRequestVerifyTokenPostErrors[keyof VerifyRequestTokenAuthRequestVerifyTokenPostErrors];

export type VerifyRequestTokenAuthRequestVerifyTokenPostResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyAuthVerifyPostData = {
  body: BodyVerifyVerifyAuthVerifyPost;
  path?: never;
  query?: never;
  url: '/auth/verify';
};

export type VerifyVerifyAuthVerifyPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyAuthVerifyPostError =
  VerifyVerifyAuthVerifyPostErrors[keyof VerifyVerifyAuthVerifyPostErrors];

export type VerifyVerifyAuthVerifyPostResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyAuthVerifyPostResponse =
  VerifyVerifyAuthVerifyPostResponses[keyof VerifyVerifyAuthVerifyPostResponses];

export type UsersCurrentUserUsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type UsersCurrentUserUsersMeGetErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserUsersMeGetResponse =
  UsersCurrentUserUsersMeGetResponses[keyof UsersCurrentUserUsersMeGetResponses];

export type UsersPatchCurrentUserUsersMePatchData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type UsersPatchCurrentUserUsersMePatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserUsersMePatchError =
  UsersPatchCurrentUserUsersMePatchErrors[keyof UsersPatchCurrentUserUsersMePatchErrors];

export type UsersPatchCurrentUserUsersMePatchResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserUsersMePatchResponse =
  UsersPatchCurrentUserUsersMePatchResponses[keyof UsersPatchCurrentUserUsersMePatchResponses];

export type UsersDeleteUserUsersIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UsersDeleteUserUsersIdDeleteErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserUsersIdDeleteError =
  UsersDeleteUserUsersIdDeleteErrors[keyof UsersDeleteUserUsersIdDeleteErrors];

export type UsersDeleteUserUsersIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserUsersIdDeleteResponse =
  UsersDeleteUserUsersIdDeleteResponses[keyof UsersDeleteUserUsersIdDeleteResponses];

export type UsersUserUsersIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UsersUserUsersIdGetErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserUsersIdGetError =
  UsersUserUsersIdGetErrors[keyof UsersUserUsersIdGetErrors];

export type UsersUserUsersIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserUsersIdGetResponse =
  UsersUserUsersIdGetResponses[keyof UsersUserUsersIdGetResponses];

export type UsersPatchUserUsersIdPatchData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UsersPatchUserUsersIdPatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserUsersIdPatchError =
  UsersPatchUserUsersIdPatchErrors[keyof UsersPatchUserUsersIdPatchErrors];

export type UsersPatchUserUsersIdPatchResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserUsersIdPatchResponse =
  UsersPatchUserUsersIdPatchResponses[keyof UsersPatchUserUsersIdPatchResponses];

export type AuthenticatedRouteAuthenticatedRouteGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/authenticated-route';
};

export type AuthenticatedRouteAuthenticatedRouteGetResponses = {
  /**
   * Response Authenticated Route Authenticated Route Get
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type AuthenticatedRouteAuthenticatedRouteGetResponse =
  AuthenticatedRouteAuthenticatedRouteGetResponses[keyof AuthenticatedRouteAuthenticatedRouteGetResponses];

export type CreateTaskDeeptodosCreateTaskPostData = {
  body: TaskCreate;
  path?: never;
  query?: never;
  url: '/deeptodos/create-task';
};

export type CreateTaskDeeptodosCreateTaskPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTaskDeeptodosCreateTaskPostError =
  CreateTaskDeeptodosCreateTaskPostErrors[keyof CreateTaskDeeptodosCreateTaskPostErrors];

export type CreateTaskDeeptodosCreateTaskPostResponses = {
  /**
   * Successful Response
   */
  201: Task;
};

export type CreateTaskDeeptodosCreateTaskPostResponse =
  CreateTaskDeeptodosCreateTaskPostResponses[keyof CreateTaskDeeptodosCreateTaskPostResponses];

export type ReadTasksDeeptodosReadTasksGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     *
     * 跳过的记录数
     */
    skip?: number;
    /**
     * Limit
     *
     * 返回的记录数
     */
    limit?: number;
    /**
     * Is Completed
     *
     * 按完成状态过滤
     */
    is_completed?: boolean | null;
    /**
     * Priority
     *
     * 按优先级过滤
     */
    priority?: number | null;
    /**
     * Category
     *
     * 按分类过滤
     */
    category?: string | null;
    /**
     * Search
     *
     * 搜索标题或描述
     */
    search?: string | null;
  };
  url: '/deeptodos/read-tasks';
};

export type ReadTasksDeeptodosReadTasksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadTasksDeeptodosReadTasksGetError =
  ReadTasksDeeptodosReadTasksGetErrors[keyof ReadTasksDeeptodosReadTasksGetErrors];

export type ReadTasksDeeptodosReadTasksGetResponses = {
  /**
   * Response Read Tasks Deeptodos Read Tasks Get
   *
   * Successful Response
   */
  200: Array<Task>;
};

export type ReadTasksDeeptodosReadTasksGetResponse =
  ReadTasksDeeptodosReadTasksGetResponses[keyof ReadTasksDeeptodosReadTasksGetResponses];

export type ReadTasksSummaryDeeptodosReadTasksSummaryGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: '/deeptodos/read-tasks-summary';
};

export type ReadTasksSummaryDeeptodosReadTasksSummaryGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadTasksSummaryDeeptodosReadTasksSummaryGetError =
  ReadTasksSummaryDeeptodosReadTasksSummaryGetErrors[keyof ReadTasksSummaryDeeptodosReadTasksSummaryGetErrors];

export type ReadTasksSummaryDeeptodosReadTasksSummaryGetResponses = {
  /**
   * Response Read Tasks Summary Deeptodos Read Tasks Summary Get
   *
   * Successful Response
   */
  200: Array<TaskSummary>;
};

export type ReadTasksSummaryDeeptodosReadTasksSummaryGetResponse =
  ReadTasksSummaryDeeptodosReadTasksSummaryGetResponses[keyof ReadTasksSummaryDeeptodosReadTasksSummaryGetResponses];

export type ReadCategoriesDeeptodosReadCategoriesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/deeptodos/read-categories';
};

export type ReadCategoriesDeeptodosReadCategoriesGetResponses = {
  /**
   * Response Read Categories Deeptodos Read Categories Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ReadCategoriesDeeptodosReadCategoriesGetResponse =
  ReadCategoriesDeeptodosReadCategoriesGetResponses[keyof ReadCategoriesDeeptodosReadCategoriesGetResponses];

export type ReadTaskDeeptodosReadTaskTaskIdGetData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: '/deeptodos/read-task/{task_id}';
};

export type ReadTaskDeeptodosReadTaskTaskIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadTaskDeeptodosReadTaskTaskIdGetError =
  ReadTaskDeeptodosReadTaskTaskIdGetErrors[keyof ReadTaskDeeptodosReadTaskTaskIdGetErrors];

export type ReadTaskDeeptodosReadTaskTaskIdGetResponses = {
  /**
   * Successful Response
   */
  200: Task;
};

export type ReadTaskDeeptodosReadTaskTaskIdGetResponse =
  ReadTaskDeeptodosReadTaskTaskIdGetResponses[keyof ReadTaskDeeptodosReadTaskTaskIdGetResponses];

export type UpdateTaskDeeptodosUpdateTaskTaskIdPatchData = {
  body: TaskUpdate;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: '/deeptodos/update-task/{task_id}';
};

export type UpdateTaskDeeptodosUpdateTaskTaskIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTaskDeeptodosUpdateTaskTaskIdPatchError =
  UpdateTaskDeeptodosUpdateTaskTaskIdPatchErrors[keyof UpdateTaskDeeptodosUpdateTaskTaskIdPatchErrors];

export type UpdateTaskDeeptodosUpdateTaskTaskIdPatchResponses = {
  /**
   * Successful Response
   */
  200: Task;
};

export type UpdateTaskDeeptodosUpdateTaskTaskIdPatchResponse =
  UpdateTaskDeeptodosUpdateTaskTaskIdPatchResponses[keyof UpdateTaskDeeptodosUpdateTaskTaskIdPatchResponses];

export type DeleteTaskDeeptodosDeleteTaskTaskIdDeleteData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: '/deeptodos/delete-task/{task_id}';
};

export type DeleteTaskDeeptodosDeleteTaskTaskIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTaskDeeptodosDeleteTaskTaskIdDeleteError =
  DeleteTaskDeeptodosDeleteTaskTaskIdDeleteErrors[keyof DeleteTaskDeeptodosDeleteTaskTaskIdDeleteErrors];

export type DeleteTaskDeeptodosDeleteTaskTaskIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTaskDeeptodosDeleteTaskTaskIdDeleteResponse =
  DeleteTaskDeeptodosDeleteTaskTaskIdDeleteResponses[keyof DeleteTaskDeeptodosDeleteTaskTaskIdDeleteResponses];

export type CompleteTaskDeeptodosCompleteTaskTaskIdPostData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: '/deeptodos/complete-task/{task_id}';
};

export type CompleteTaskDeeptodosCompleteTaskTaskIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CompleteTaskDeeptodosCompleteTaskTaskIdPostError =
  CompleteTaskDeeptodosCompleteTaskTaskIdPostErrors[keyof CompleteTaskDeeptodosCompleteTaskTaskIdPostErrors];

export type CompleteTaskDeeptodosCompleteTaskTaskIdPostResponses = {
  /**
   * Successful Response
   */
  200: Task;
};

export type CompleteTaskDeeptodosCompleteTaskTaskIdPostResponse =
  CompleteTaskDeeptodosCompleteTaskTaskIdPostResponses[keyof CompleteTaskDeeptodosCompleteTaskTaskIdPostResponses];
