// Auto-generated by vite-plugin-openapi-ts
// Do not edit this file manually

/**
 * Schema: BearerResponse
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_BearerResponse {
  access_token: string;
  token_type: string;
}

/**
 * Schema: Body_auth_jwt_login_auth_jwt_login_post
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_Body_auth_jwt_login_auth_jwt_login_post {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}

/**
 * Schema: Body_reset_forgot_password_auth_forgot_password_post
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_Body_reset_forgot_password_auth_forgot_password_post {
  email: string;
}

/**
 * Schema: Body_reset_reset_password_auth_reset_password_post
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_Body_reset_reset_password_auth_reset_password_post {
  token: string;
  password: string;
}

/**
 * Schema: Body_verify_request_token_auth_request_verify_token_post
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_Body_verify_request_token_auth_request_verify_token_post {
  email: string;
}

/**
 * Schema: Body_verify_verify_auth_verify_post
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_Body_verify_verify_auth_verify_post {
  token: string;
}

/**
 * Schema: ErrorModel
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_ErrorModel {
  detail: string | Record<string, string>;
}

/**
 * Schema: HTTPValidationError
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_HTTPValidationError {
  detail?: Array<SCHEME_ValidationError>;
}

/**
 * Schema: Task
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_Task {
  /** 任务标题 */
  title: string;
  /** 任务描述 */
  description?: string | null;
  /** 是否完成 */
  is_completed?: boolean;
  /** 优先级(1-低, 2-中, 3-高) */
  priority?: number;
  /** 任务分类 */
  category?: string;
  id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Schema: TaskCreate
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_TaskCreate {
  /** 任务标题 */
  title: string;
  /** 任务描述 */
  description?: string | null;
  /** 是否完成 */
  is_completed?: boolean;
  /** 优先级(1-低, 2-中, 3-高) */
  priority?: number;
  /** 任务分类 */
  category?: string;
}

/**
 * Schema: TaskSummary
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_TaskSummary {
  id: string;
  title: string;
  is_completed: boolean;
  priority: number;
  category: string;
  created_at: string;
}

/**
 * Schema: TaskUpdate
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_TaskUpdate {
  title?: string | null;
  description?: string | null;
  is_completed?: boolean | null;
  priority?: number | null;
  category?: string | null;
}

/**
 * Schema: UserCreate
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_UserCreate {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
}

/**
 * Schema: UserRead
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_UserRead {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
}

/**
 * Schema: UserUpdate
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_UserUpdate {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
}

/**
 * Schema: ValidationError
 * @description Generated from OpenAPI schema
 */
export interface SCHEME_ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: any;
  ctx?: Record<string, any>;
}

